#- pipeline.id: nmap
#  path.config: "/usr/share/logstash/config/pipelines/nmap.conf"
- pipeline.id: filebeat
  # pipeline.workers: 32
  #pipeline.batch.size: 500
  path.config: "/usr/share/logstash/config/pipelines/host-filebeat.conf"
  #- pipeline.id: filebeat2
  # pipeline.workers: 32
  #pipeline.batch.size: 500
  #path.config: "/usr/share/logstash/config/pipelines/host-filebeat2.conf"
- pipeline.id: metricbeat
  #pipeline.workers: 16
  #pipeline.batch.size: 250
  path.config: "/usr/share/logstash/config/pipelines/host-metricbeat.conf"
- pipeline.id: heartbeat
  #pipeline.workers: 8
  #pipeline.batch.size: 500
  path.config: "/usr/share/logstash/config/pipelines/host-heartbeat.conf"
#- pipeline.id: pcap
#  pipeline.workers: 8
#  pipeline.batch.size: 500
#  path.config: "/usr/share/logstash/config/pipelines/pcap-filebeat.conf"
#- pipeline.id: packetbeat
#  path.config: "/usr/share/logstash/config/pipelines/host-packetbeat.conf"

# - pipeline.id: test
#   pipeline.workers: 1
#   pipeline.batch.size: 1
#   config.string: "input { generator {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
# - pipeline.id: another_test
#   queue.type: persisted
#   path.config: "/tmp/logstash/*.config"
#
#   pipeline.id: mylogs
#   config.string: "input { generator {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
#   path.config: "/etc/conf.d/logstash/myconfig.cfg"
#   pipeline.workers: 1 (actually defaults to number of CPUs)
#   pipeline.batch.size: 125
#   pipeline.batch.delay: 50
#   queue.type: memory
#   queue.page_capacity: 64mb
#   queue.max_events: 0
#   queue.max_bytes: 1024mb
#   queue.checkpoint.acks: 1024
#   queue.checkpoint.writes: 1024
#   queue.checkpoint.interval: 1000
#   dead_letter_queue.enable: false
#   dead_letter_queue.max_bytes: 1024mb
#   path.dead_letter_queue:
